r"""Contain modules."""

from __future__ import annotations

__all__ = [
    "ArithmeticalMeanIndicator",
    "Asinh",
    "AsinhMSELoss",
    "AsinhSmoothL1Loss",
    "AverageFusion",
    "BaseAlphaActivation",
    "BaseRelativeIndicator",
    "BinaryFocalLoss",
    "BinaryFocalLossWithLogits",
    "BinaryPoly1Loss",
    "BinaryPoly1LossWithLogits",
    "Clamp",
    "ClassicalRelativeIndicator",
    "ConcatFusion",
    "ExU",
    "Exp",
    "ExpSin",
    "Expm1",
    "Gaussian",
    "GeneralRobustRegressionLoss",
    "GeometricMeanIndicator",
    "Laplacian",
    "Log",
    "Log1p",
    "MaximumMeanIndicator",
    "MinimumMeanIndicator",
    "MomentMeanIndicator",
    "MultiQuadratic",
    "MulticlassFlatten",
    "MultiplicationFusion",
    "NLinear",
    "PoissonRegressionLoss",
    "Quadratic",
    "QuantileRegressionLoss",
    "ReLUn",
    "RelativeLoss",
    "RelativeMSELoss",
    "RelativeSmoothL1Loss",
    "ResidualBlock",
    "ReversedRelativeIndicator",
    "SafeExp",
    "SafeLog",
    "Sin",
    "Sinh",
    "Snake",
    "SquaredReLU",
    "Squeeze",
    "SumFusion",
    "ToBinaryLabel",
    "ToCategoricalLabel",
    "ToFloat",
    "ToLong",
    "TransformedLoss",
    "View",
]

from sonnix.modules.activations import (
    Asinh,
    BaseAlphaActivation,
    Exp,
    Expm1,
    ExpSin,
    Gaussian,
    Laplacian,
    Log,
    Log1p,
    MultiQuadratic,
    Quadratic,
    ReLUn,
    SafeExp,
    SafeLog,
    Sin,
    Sinh,
    Snake,
    SquaredReLU,
)
from sonnix.modules.classification import ToBinaryLabel, ToCategoricalLabel
from sonnix.modules.dtype import ToFloat, ToLong
from sonnix.modules.exu import ExU
from sonnix.modules.fusion import (
    AverageFusion,
    ConcatFusion,
    MultiplicationFusion,
    SumFusion,
)
from sonnix.modules.fusion.clamp import Clamp
from sonnix.modules.loss import (
    ArithmeticalMeanIndicator,
    AsinhMSELoss,
    AsinhSmoothL1Loss,
    BaseRelativeIndicator,
    BinaryFocalLoss,
    BinaryFocalLossWithLogits,
    BinaryPoly1Loss,
    BinaryPoly1LossWithLogits,
    ClassicalRelativeIndicator,
    GeneralRobustRegressionLoss,
    GeometricMeanIndicator,
    MaximumMeanIndicator,
    MinimumMeanIndicator,
    MomentMeanIndicator,
    PoissonRegressionLoss,
    QuantileRegressionLoss,
    RelativeLoss,
    RelativeMSELoss,
    RelativeSmoothL1Loss,
    ReversedRelativeIndicator,
    TransformedLoss,
)
from sonnix.modules.nlinear import NLinear
from sonnix.modules.residual import ResidualBlock
from sonnix.modules.shape import MulticlassFlatten, Squeeze, View
